source 'https://rubygems.org'

gem 'rake'

# jekyll, which builds it all
gem 'jekyll', '~>4.3.2'

# JSON
gem 'json'

# SASS for CSS
gem 'sass'

# For `rake watch`
gem 'rb-fsevent'

# Redcarpet for Markdown
gem 'redcarpet'

# For markdown header cleanup
gem 'sanitize'
